from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.db.models import Q
from .models import Doctor

@login_required
def doctor_list(request):
    """Display list of all doctors"""
    doctors = Doctor.objects.all().select_related('user').order_by('-created_at')
    
    # Search functionality
    search_query = request.GET.get('search', '')
    if search_query:
        doctors = doctors.filter(
            Q(employee_id__icontains=search_query) |
            Q(user__first_name__icontains=search_query) |
            Q(user__last_name__icontains=search_query) |
            Q(specialization__icontains=search_query) |
            Q(phone_number__icontains=search_query)
        )
    
    context = {
        'doctors': doctors,
        'search_query': search_query,
        'total_doctors': Doctor.objects.count(),
    }
    return render(request, 'doctors/doctor_list.html', context)


@login_required
def doctor_detail(request, pk):
    """Display detailed view of a doctor"""
    doctor = get_object_or_404(Doctor, pk=pk)
    from appointments.models import Appointment
    
    appointments = Appointment.objects.filter(doctor=doctor).order_by('-appointment_date')
    total_appointments = appointments.count()
    completed_appointments = appointments.filter(status='COMPLETED').count()
    pending_appointments = appointments.filter(status='PENDING').count()
    
    context = {
        'doctor': doctor,
        'appointments': appointments[:10],
        'total_appointments': total_appointments,
        'completed_appointments': completed_appointments,
        'pending_appointments': pending_appointments,
    }
    return render(request, 'doctors/doctor_detail.html', context)


@login_required
def doctor_create(request):
    """Create a new doctor"""
    if request.method == 'POST':
        try:
            # Get form data
            first_name = request.POST.get('first_name', '').strip()
            last_name = request.POST.get('last_name', '').strip()
            username = request.POST.get('username', '').strip()
            password = request.POST.get('password', '').strip()
            email = request.POST.get('email', '').strip()
            phone_number = request.POST.get('phone_number', '').strip()
            
            # Professional information
            specialization = request.POST.get('specialization', '').strip()
            qualification = request.POST.get('qualification', '').strip()
            experience = request.POST.get('experience', 0)
            consultation_fee = request.POST.get('consultation_fee', 0)
            room_number = request.POST.get('room_number', '').strip()
            available_days = request.POST.get('available_days', '').strip()
            available_time = request.POST.get('available_time', '').strip()
            is_available = request.POST.get('is_available') == 'on'
            
            # Validate required fields
            if not all([first_name, last_name, username, password, email, specialization, qualification]):
                messages.error(request, 'All required fields must be filled!')
                return render(request, 'doctors/doctor_form.html', {
                    'is_update': False
                })
            
            # Check if username already exists
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Username "{username}" already exists!')
                return render(request, 'doctors/doctor_form.html', {
                    'is_update': False
                })
            
            # Check if email already exists
            if User.objects.filter(email=email).exists():
                messages.error(request, f'Email "{email}" already exists!')
                return render(request, 'doctors/doctor_form.html', {
                    'is_update': False
                })
            
            # Create user
            user = User.objects.create_user(
                username=username,
                email=email,
                first_name=first_name,
                last_name=last_name,
                password=password
            )
            
            # Create doctor (employee_id will be auto-generated by model)
            doctor = Doctor.objects.create(
                user=user,
                specialization=specialization,
                qualification=qualification,
                experience_years=int(experience) if experience else 0,
                consultation_fee=float(consultation_fee) if consultation_fee else 0,
                phone_number=phone_number,
                room_number=room_number,
                available_days=available_days,
                available_time=available_time,
                is_available=is_available
            )
            
            messages.success(request, f'Doctor {doctor.get_full_name()} (ID: {doctor.employee_id}) added successfully!')
            return redirect('doctors:doctor_detail', pk=doctor.pk)
            
        except ValueError as e:
            messages.error(request, 'Invalid number format. Please check experience and consultation fee.')
            return render(request, 'doctors/doctor_form.html', {
                'is_update': False
            })
        except Exception as e:
            messages.error(request, f'Error adding doctor: {str(e)}')
            return render(request, 'doctors/doctor_form.html', {
                'is_update': False
            })
    
    # GET request - show form
    context = {
        'is_update': False
    }
    return render(request, 'doctors/doctor_form.html', context)


@login_required
def doctor_update(request, pk):
    """Update an existing doctor"""
    doctor = get_object_or_404(Doctor, pk=pk)
    
    if request.method == 'POST':
        try:
            # Update user information
            doctor.user.first_name = request.POST.get('first_name', '').strip()
            doctor.user.last_name = request.POST.get('last_name', '').strip()
            doctor.user.email = request.POST.get('email', '').strip()
            
            # Update password only if provided
            new_password = request.POST.get('password', '').strip()
            if new_password:
                doctor.user.set_password(new_password)
            
            doctor.user.save()
            
            # Update doctor information
            doctor.specialization = request.POST.get('specialization', '').strip()
            doctor.qualification = request.POST.get('qualification', '').strip()
            doctor.experience_years = int(request.POST.get('experience', 0))
            doctor.consultation_fee = float(request.POST.get('consultation_fee', 0))
            doctor.phone_number = request.POST.get('phone_number', '').strip()
            doctor.room_number = request.POST.get('room_number', '').strip()
            doctor.available_days = request.POST.get('available_days', '').strip()
            doctor.available_time = request.POST.get('available_time', '').strip()
            doctor.is_available = request.POST.get('is_available') == 'on'
            
            doctor.save()
            
            messages.success(request, f'Doctor {doctor.get_full_name()} updated successfully!')
            return redirect('doctors:doctor_detail', pk=doctor.pk)
            
        except ValueError:
            messages.error(request, 'Invalid number format. Please check experience and consultation fee.')
        except Exception as e:
            messages.error(request, f'Error updating doctor: {str(e)}')
    
    # GET request - show form with doctor data
    context = {
        'doctor': doctor,
        'is_update': True
    }
    return render(request, 'doctors/doctor_form.html', context)


@login_required
def doctor_delete(request, pk):
    """Delete a doctor"""
    doctor = get_object_or_404(Doctor, pk=pk)
    
    if request.method == 'POST':
        doctor_name = doctor.get_full_name()
        doctor.user.delete()  # This will also delete the doctor due to CASCADE
        messages.success(request, f'Doctor {doctor_name} deleted successfully!')
        return redirect('doctors:doctor_list')
    
    return redirect('doctors:doctor_detail', pk=pk)