# Generated by Django 4.2.7 on 2025-12-15 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='bill',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial Payment')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='bill',
            table=None,
        ),
    ]
