# Generated by Django 4.2.7 on 2025-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Box', 'Box'), ('Bottle', 'Bottle'), ('Strip', 'Strip'), ('Vial', 'Vial'), ('Tube', 'Tube')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='medicine',
            table=None,
        ),
    ]
