# Generated by Django 4.2.7 on 2025-12-16 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash'), ('MOBILE_BANKING', 'Mobile Banking')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation Fee'), ('MEDICINE_SALE', 'Medicine Sale'), ('LAB_TEST', 'Lab Test'), ('ADMISSION', 'Admission Fee'), ('OTHER_INCOME', 'Other Income'), ('SALARY', 'Salary Payment'), ('PURCHASE', 'Purchase'), ('UTILITY', 'Utility Bills'), ('RENT', 'Rent'), ('MAINTENANCE', 'Maintenance'), ('MEDICINE_PURCHASE', 'Medicine Purchase'), ('EQUIPMENT', 'Equipment'), ('OTHER_EXPENSE', 'Other Expense')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_to', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('CARD', 'Card'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation Fee'), ('MEDICINE_SALE', 'Medicine Sale'), ('LAB_TEST', 'Lab Test'), ('ADMISSION', 'Admission Fee'), ('OTHER_INCOME', 'Other Income'), ('SALARY', 'Salary Payment'), ('PURCHASE', 'Purchase'), ('UTILITY', 'Utility Bills'), ('RENT', 'Rent'), ('MAINTENANCE', 'Maintenance'), ('MEDICINE_PURCHASE', 'Medicine Purchase'), ('EQUIPMENT', 'Equipment'), ('OTHER_EXPENSE', 'Other Expense')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('CARD', 'Card'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.account')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation Fee'), ('MEDICINE_SALE', 'Medicine Sale'), ('LAB_TEST', 'Lab Test'), ('ADMISSION', 'Admission Fee'), ('OTHER_INCOME', 'Other Income'), ('SALARY', 'Salary Payment'), ('PURCHASE', 'Purchase'), ('UTILITY', 'Utility Bills'), ('RENT', 'Rent'), ('MAINTENANCE', 'Maintenance'), ('MEDICINE_PURCHASE', 'Medicine Purchase'), ('EQUIPMENT', 'Equipment'), ('OTHER_EXPENSE', 'Other Expense')], max_length=30)),
                ('month', models.DateField()),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('category', 'month')},
            },
        ),
    ]
